# ===========================================================
# Main File
# ===========================================================

"""
This file is going to conect the GMSH mesh generation with the SU2 solver with additional post processing results.

General structure:

- Hermite generation script with main input parameters
- Meshing generation script with GMSH. Takes as input the Hermite script and generates the mesh.
- Solver call script with SU2. Takes as input the mesh generated by GMSH and runs the solver.
- Post-processing script with additional analysis and visualization with PARAVIEW (hopefully).

"""

# ==========================================================
# Libraries
# ==========================================================
import sys
import os
import gmsh
import numpy as np
import subprocess
import pandas as pd

from Paraview_post import paraview_postprocessing
# Here go functions related to hermite, mesh scripts and more
# ==========================================================


#  Working directory path
path = os.path.dirname(os.path.abspath(__file__))
# Change the current working directory to the script's directory
os.chdir(path)

# ==============================================================
# Functions reprensenting the Hermite generation and mesh generation are called here
def hermite(x,y):
    """
    Hermite function example
    """
    if x == 1 and y == 1:
        return True
    else:
        return None

def mesh_generation(file_name, x, y):
    """
    GMSH mesh generation function
    Input: Hermite function parameters
    Output: GMSH mesh file
    """
    if hermite(x, y):
        return os.path.join(path, file_name)


def run_solver(config_file, output_files_path):
    """
    Input =  configuration file with instructions for SU2 
    output = Output files path for postprocessing in gmsh
    """
    result = subprocess.run(
        ["mpirun ", "-n ", "4 ","SU2_CFD ", config_file],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    if result.returncode != 0:
        print("Error:", result.stderr)

    Surface_output_file = os.path.join(output_files_path, "surface_flow.vtu")
    
    Volume_output_file = os.path.join(output_files_path, "flow.vtu")
    return Surface_output_file, Volume_output_file


def paraview_caller(Python_file, input_file, output_file):
    """
    This function execute a python script runing the commands on paraview to export the pressure coefficient over a surface

    INput = Python script with Paraview commands and path to surface_flow.vtu
    output = CSV file containing Cp distribution along a given surface, a bumb in this case.

    Note: ThE Python script must be at the working directory
    """
    
    result = subprocess.run(
        ["pvpython ", Python_file, input_file, output_file],
        capture_output=True,
        text=True
    )

    return None



# ==============================================================
# ==============================================================
# Example
# ==============================================================
mesh_file_name = "mesh_channel_256x128.su2"

# Mesh generation function call
mesh = mesh_generation(mesh_file_name, 1, 1)

# Configuration file
config_file = os.path.join(path, "inv_channel.cfg")

# Solver call
surface_sol_file, volume_sol_file = run_solver(config_file, path)

# PARAVIEW POST PROCESSING

# Script
paraview_script = "Paraview_post.py"

# Output file name
Cp_csv_path = "Cp_dist.csv"

# File generation
paraview_caller(paraview_script, surface_sol_file, Cp_csv_path)

Cp_csv = pd.read_csv(Cp_csv_path)

paraview_script = "Paraview_post.py"

# Output file name
Cp_csv_path = "Cp_dist.csv"

surface_sol_file = "surface_flow.vtu"
# File generation
paraview_caller(paraview_script, surface_sol_file, Cp_csv_path)

Cp_csv = pd.read_csv(Cp_csv_path)






                    