# ===========================================================
# Main File
# ===========================================================

"""
This file is going to conect the GMSH mesh generation with the SU2 solver with additional post processing results.

General structure:

- Hermite generation script with main input parameters
- Meshing generation script with GMSH. Takes as input the Hermite script and generates the mesh.
- Solver call script with SU2. Takes as input the mesh generated by GMSH and runs the solver.
- Post-processing script with additional analysis and visualization with PARAVIEW (hopefully).

"""

# ==========================================================
# Libraries
# ==========================================================
import sys
import os
import gmsh
import numpy as np
import subprocess
import pandas as pd
from Mesh_2D_copia import meshgen_2D
#from Paraview_post import paraview_postprocessing
# Here go functions related to hermite, mesh scripts and more
# ==========================================================


#  Working directory path
path = os.path.dirname(os.path.abspath(__file__))
# Change the current working directory to the script's directory
os.chdir(path)

# ==============================================================
# Functions reprensenting the Hermite generation and mesh generation are called here


def modify_params_cfg(archivo_cfg, parametro, nuevo_valor):
    with open(archivo_cfg, 'r') as f:
        lineas = f.readlines()

    with open(archivo_cfg, 'w') as f:
        for linea in lineas:
            # Si la línea define ese parámetro (ignorando comentarios y espacios)
            if linea.strip().startswith(parametro + '='):
                f.write(f"{parametro}= {nuevo_valor}\n")
            else:
                f.write(linea)


def run_solver(config_file, output_files_path, n_processors=4, path=None):
    """
    Input =  configuration file with instructions for SU2 
    output = Output files path for postprocessing in gmsh
    """
    modify_params_cfg(config_file, "MESH_FILENAME", path)

    result = subprocess.run(
        ["mpiexec.exe ", "-n", str(n_processors), "SU2_CFD", config_file],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    if result.returncode != 0:
        print("Error:", result.stderr)
    
    
    Surface_output_file = os.path.join(output_files_path, "surface_flow.vtu")
        
    Volume_output_file = os.path.join(output_files_path, "flow.vtu")
    return Surface_output_file, Volume_output_file


def paraview_caller(Python_file, input_file, output_file):
    """
    This function execute a python script runing the commands on paraview to export the pressure coefficient over a surface

    INput = Python script with Paraview commands and path to surface_flow.vtu
    output = CSV file containing Cp distribution along a given surface, a bumb in this case.

    Note: ThE Python script must be at the working directory
    """
    
    result = subprocess.run(
        ["pvpython ", Python_file, input_file, output_file],
        capture_output=True,
        text=True
    )

    return None




# ==============================================================
# ==============================================================
# Example
# ==============================================================
mesh_file_name = "mesh_rocket_2d.su2"

# Mesh generation function call

meshgen_2D(1, 1, config = {"filename" : "Mesh.su2"}, path_f = os.path.join(path, "Integration"))


# Configuration file
config_file = os.path.join(path, "Integration\\exp.cfg")
print("Configuration file path:", config_file)
# Solver call
surface_sol_file, volume_sol_file = run_solver(config_file, os.path.join(path, "Integration"),
                                                n_processors=4, path=os.path.join(path, "Integration", mesh_file_name))

# PARAVIEW POST PROCESSING
"""
# Script
paraview_script = "Paraview_post.py"

# Output file name
Cp_csv_path = "Cp_dist.csv"

# File generation
paraview_caller(paraview_script, surface_sol_file, Cp_csv_path)

Cp_csv = pd.read_csv(Cp_csv_path)

paraview_script = "Paraview_post.py"

# Output file name
Cp_csv_path = "Cp_dist.csv"

surface_sol_file = "surface_flow.vtu"
# File generation
paraview_caller(paraview_script, surface_sol_file, Cp_csv_path)

Cp_csv = pd.read_csv(Cp_csv_path)
"""






                    