# ===========================================================
# Main File
# ===========================================================

"""
This file is going to conect the GMSH mesh generation with the SU2 solver with additional post processing results.

General structure:

- Hermite generation script with main input parameters
- Meshing generation script with GMSH. Takes as input the Hermite script and generates the mesh.
- Solver call script with SU2. Takes as input the mesh generated by GMSH and runs the solver.
- Post-processing script with additional analysis and visualization with PARAVIEW (hopefully).

"""

# ==========================================================
# Libraries
# ==========================================================
import sys
import os
import gmsh
import numpy as np
import subprocess
import pandas as pd
from Mesh_2D import meshgen_2D

# PATH DEFINITION
#  Working directory path
folder = os.path.dirname(os.path.abspath(__file__))
# Change the current working directory to the script's directory
os.chdir(folder)

#========================================================================================
# Function to run the SU2 solver with a given configuration file and output path
#========================================================================================
def run_solver(config_file, output_files_path, n_processors=4):
    """
    Input =  configuration file with instructions for SU2 
    output = Output files path for postprocessing in gmsh
    """

    result = subprocess.run(
        ["mpiexec.exe", "-n", str(n_processors), "SU2_CFD", config_file],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    if result.returncode != 0:
        print("Error:", result.stderr)
    
    
    Surface_output_file = os.path.join(output_files_path, "surface_flow.vtu")
        
    Volume_output_file = os.path.join(output_files_path, "flow.vtu")
    return Surface_output_file, Volume_output_file
#========================================================================================

#========================================================================================
# Config and mesh files 
#========================================================================================
config_file = "Rocket_2d.cfg"
mesh_file_name = "Mesh.su2"
#========================================================================================

#========================================================================================
# Mesh generation function call
#========================================================================================
#meshgen_2D(1, 1, config = {"filename" : "Mesh.su2"}, folder = folder)
#========================================================================================


Surface_output_file, Volume_output_file = run_solver(config_file, folder, n_processors=4)