# ===========================================================
# Test file
# ===========================================================

"""
This file is going to conect the GMSH mesh generation with the SU2 solver with additional post processing results.

General structure:

- Hermite generation script with main input parameters
- Meshing generation script with GMSH. Takes as input the Hermite script and generates the mesh.
- Solver call script with SU2. Takes as input the mesh generated by GMSH and runs the solver.
- Post-processing script with additional analysis and visualization with PARAVIEW (hopefully).

"""

# ==========================================================
# Libraries
# ==========================================================

import os
import numpy as np
import subprocess
import pandas as pd
from Mesh_2D_new import meshgen_2D
import shutil
from scipy.optimize import minimize
import matplotlib.pyplot as plt

#========================================================================================
# PATH DEFINITION
#========================================================================================

#  Working directory path
folder = os.path.dirname(os.path.abspath(__file__))


# Executables paths
MPIEXEC = shutil.which("mpiexec")
SU2_CFD = shutil.which("SU2_CFD")
PVPYTHON = shutil.which("pvpython")

# Change the current working directory to the script's directory
os.chdir(folder)




def run_solver(config_file, output_files_path, n_processors=4):
    """
    Functions that calls SU2 and runs a config_file in parallel
    Inputs:
    - config_file: configuration file name
    - output_files_path: folder where solution files will be stored
    -n_processors: number of processors to use in parallel
    Outputs:
    - surface_output_file: path to the surface flow output file
    - volume_output_file: path to the volume flow output file    

    """
    # Files paths and folder definitions    
    config_file = os.path.abspath(config_file)
    output_files_path = os.path.abspath(output_files_path)
    print(f"Running SU2 with configuration file: {config_file}")

    # Execution on terminal
    try:
        cmd = [MPIEXEC, "-n", str(n_processors), SU2_CFD, config_file]
        subprocess.run(
            cmd,
            cwd=output_files_path,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"SU2 falló con código {e.returncode}") from e

    surface_output_file = os.path.join(output_files_path, "surface_flow.vtu")
    volume_output_file = os.path.join(output_files_path, "flow.vtu")

    for f in (surface_output_file, volume_output_file):
        if not os.path.exists(f):
            raise FileNotFoundError(f"SU2 terminó pero no se generó {f}")

    return surface_output_file, volume_output_file











#========================================================================================
# HERMITE PARAMETERS
#========================================================================================
a = 1
b = 1

#========================================================================================
# Config and mesh files 
#========================================================================================
config_file = "Rocket_2d.cfg"
mesh_file_name = "Mesh.su2"
#========================================================================================

#========================================================================================
# Mesh generation function call
#========================================================================================
#mesh_file_path = meshgen_2D(a, b, config = {"filename" : mesh_file_name})

#========================================================================================

#========================================================================================
# Solver call
#========================================================================================
surface_output_file, volume_output_file = run_solver(config_file, folder, n_processors=4)
#========================================================================================
